### ISSUE TITLE
Support: Gemini Pro Vision

### ISSUE THREAD

**Issue by doggy8088** [mscraftsman/generative-ai#4]
Would you support `Gemini Pro Vision` API in your package?

**Comment by jochenkirstaetter** [comment]
Hi @doggy8088 

What do you mean? It is already in since the very commit.
See [tests](https://github.com/mscraftsman/generative-ai/tree/main/tests) and there in particular the files [GoogleAi_GeminiProVision_Should.cs](https://github.com/mscraftsman/generative-ai/blob/main/tests/Mscc.GenerativeAI/GoogleAi_GeminiProVision_Should.cs) and [VertexAi_GeminiProVision_Should.cs](https://github.com/mscraftsman/generative-ai/blob/main/tests/Mscc.GenerativeAI/VertexAi_GeminiProVision_Should.cs)

The only change needed is to specify the model: `Model.GeminiProVision` and you are good to go.
_Hint:_ See the type `Model` which lists all model names supported by the package.

All other methods work as expected. Since release 0.9.0 there are compatibility methods for the older PaLM 2 models.

Please let me know what's missing and I'll look into it.

**Comment by doggy8088** [comment]
I see. I didn't realize that. It because I don't see any example in your README.

**Comment by jochenkirstaetter** [comment]
Kindly look at the tests... 
There is everything coded with examples. Every feature and functionality has a test.

**Comment by jochenkirstaetter** [comment]
Dear @doggy8088 

The README has been extended. Thanks for pointing this out.

**Comment by doggy8088** [comment]
@jochenkirstaetter Don't you consider let `TestExtensions.ReadImageFileBase64Async` built-in to your library?

**Comment by jochenkirstaetter** [comment]
@doggy8088 yes, that's what I did today. There's going to be a `Generative Content Request.AddMedia` method with the next release that abstracts the handling of images. Probably tonight. Still writing the tests and checking against VertexAI. But it works with GoogleAI.

Bear with me...

**Comment by doggy8088** [comment]
Nice to hear. 👍
